[package]
name = "tower-batch"
version = "0.1.0"
edition = "2021"
authors = ["Borislav Borisov <chmodas@astutebits.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chmodas/tower-batch"
homepage = "https://github.com/chmodas/tower-batch"
documentation = "https://docs.rs/tower-batch"
description = """
`tower-batch` is a Tower middleware that allows you to buffer requests for batch processing
until the buffer reaches a maximum size OR a maximum duration elapses.
"""
categories = ["asynchronous", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures", "service"]
rust-version = "1.71.0"

exclude = [
  ".gitignore",
  ".github",
  "README.md"
]

[dependencies]

futures-core = "0.3"
pin-project-lite = "0.2"
tokio = { version = "1", features = ["sync", "time", "rt"] }
tokio-util = { version = "0.7", default-features = false }
tracing = "0.1"
tower = "0.5"

[dev-dependencies]

tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
futures = "0.3"
tokio = { version = "1", features = ["macros", "sync", "test-util", "rt-multi-thread"] }
tokio-test = "0.4"
tower = { version = "0.5", features = ["full"] }
tower-test = "0.4"
rusqlite = { version = "0.39", features = ["bundled", "array"] }

