name: CI Build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cargo Cache
        uses: Swatinem/rust-cache@v1
      - name: Build and test
        run: |
          cargo clippy --all-targets --all-features --  -D warnings
          cargo test
